# Generated by Django 4.0.5 on 2022-06-17 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['title'], 'verbose_name_plural': 'series'},
        ),
        migrations.AlterField(
            model_name='course',
            name='hero_image',
            field=models.ImageField(null=True, upload_to='courses', verbose_name='Course image'),
        ),
        migrations.AlterField(
            model_name='course',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.series', verbose_name='series'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Course title'),
        ),
    ]
