# Generated by Django 4.0.6 on 2022-07-09 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_content_content_type_alter_course_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='Module',
            new_name='module',
        ),
    ]
